package zhikrullah.online.shop.Model.Enums;

public enum Countries {
    Afghanistan("Afghanistan"),
    Albania("Ablania"),
    Algeria("Algeria"),
    American_Samoa("American Samao"),
    Andorra("Andorra"),
    Angola("Angola"),
    Anguilla("Anguilla"),
    Argentina("Argentina"),
    Armenia("Armenia"),
    Aruba("Aruba"),
    Australia("Australia"),
    Austria("Austria"),
    Azerbaijan("Azerbaijan"),
    The_Bahamas("The Bahamas"),
    Bahrain("Bahrain"),
    Bangladesh("Bangladesh"),
    Barbados("Barbados"),
    Belarus("Belarus"),
    Belgium("Belgium"),
    Belize("Belize"),
    Benin("Benin"),
    Bermuda("Bermuda"),
    Bhutan("Bhutan"),
    Bolivia("Bolivia"),
    Botswana("Botswana"),
    Brazil("Brazil"),
    British_Virgin_Island("British Virgin Islands"),
    Brunei("Brunei"),
    Bulgaria("Bulgeria"),
    Burkina_Faso("Burkina Faso"),
    Burma("Burma"),
    Burundi("Burundi"),
    Cambodia("Cambodia"),
    Cameroon("Cameroon"),
    Canada("Canada"),
    Cape_Verde("Cape Verde"),
    Cayman_Islands("Cayman Islands"),
    Central_African_Republic("Central African Republic"),
    Chad("Chad"),
    Chile("Chile"),
    China("China"),
    Colombia("Colombia"),
    Democratic_Republic_of_Congo("Democratic Republic of Congo"),
    Comoros("Comoros"),
    Republic_of_the_Congo("Republic of the Congo"),
    Cook_Islands("Cook Islands"),
    Costa_Rica("Costa Rica"),
    Ivory_Coast("Ivory Coast"),
    Croatia("Croatia"),
    Cuba("Cuba"),
    Cyprus("Cyprus"),
    Czech_Republic("Czech Republic"),
    Denmark("Denmark"),
    Djibouti("Djibouti"),
    Dominica("Dominica"),
    Dominican_Republic("Dominican Republic"),
    East_Timor("East Timor"),
    Ecuador("Ecuador"),
    Egypt("Egypt"),
    El_Salvador("El Salvador"),
    Equatorial_Guinea("Equatorial Guinea"),
    Eritrea("Eritrea"),
    Estonia("Estonia"),
    Ethiopia("Ethiopoa"),
    Faroe_Islands("Faroe Islands"),
    Fiji("Fiji"),
    Finland("Finland"),
    France("France"),
    French_Guiana("French Guiana"),
    French_Polynesia("French Polynesia"),
    Gabon("Gabon"),
    Gambia_The("The Gambia"),
    Gaza_Strip("Gaza Strip"),
    Georgia("Georgia"),
    Germany("Germany"),
    Ghana("Ghana"),
    Gibraltar("Gibralta"),
    Greece("Greece"),
    Greenland("Greenland"),
    Grenada("Grenada"),
    Guadeloupe("Guadeloupe"),
    Guam("Guam"),
    Guatemala("Guatamala"),
    Guernsey("Guernsey"),
    Guinea("Guinea"),
    Guinea_Bissau("Guinea Bissau"),
    Guyana("Guyana"),
    Haiti("Haiti"),
    Honduras("Honduras"),
    Hungary("Hungary"),
    Iceland("Iceland"),
    India("India"),
    Indonesia("Indonesias"),
    Irans("Iran"),
    Iraq("Iraq"),
    Ireland("Ireland"),
    Isle_Of_Man("Isle of Man"),
    Israel("Isreal"),
    Italy("Italy"),
    Jamaica("Jamaica"),
    Japan("Japan"),
    Jersey("Jersey"),
    Jordan("Jordan"),
    Kazakhstan("Kazakhstan"),
    Kenya("Kenya"),
    Kiribati("Kiribati"),
    North_Korea("North Korea"),
    South_Korea("South Korea"),
    Kuwait("Kuwait"),
    Kyrgyzstan("Kyrgyzstan"),
    Laos("Laos"),
    Latvia("Latvia"),
    Lebanon("Lebanon"),
    Lesotho("Lesotho"),
    Liberia("Liberia"),
    Libya("Libya"),
    Liechtenstein("Liechtenstein"),
    Lithuania("Lithuania"),
    Luxembourg("Luxembourg"),
    Macau("Macau"),
    Macedonia("Macedonia"),
    Madagascar("Madagascar"),
    Malawi("Malawi"),
    Malaysia("Malaysia"),
    Maldives("Maldives"),
    Mali("Mali"),
    Malta("Malta"),
    Marshall_Islands("Marshall Islands"),
    Martinique("Martinique"),
    Mauritania("Mauritania"),
    Mauritius("Mauritius"),
    Mayotte("Mayotte"),
    Mexico("Mexice"),
    Micronesia("Mocronesia"),
    Moldova("Moldova"),
    Monaco("Monaco"),
    Mongolia("Mongolia"),
    Montserrat("Montserrat"),
    Morocco("Morocco"),
    Mozambique("Mozambique"),
    Namibia("Namibia"),
    Nauru("Nauru"),
    Nepal("Nepal"),
    Netherlands("Netherlands"),
    Netherlands_Antilles("Netherlands Antilles"),
    New_Caledonia("New Caledonia"),
    New_Zealand("New Zealand"),
    Nicaragua("Nicaragua"),
    Niger("Niger"),
    Nigeria("Nigeria"),
    North_Mariana_Islands("North Mariana Islands"),
    Norway("Norway"),
    Oman("Oman"),
    Pakistan("Pakistan"),
    Palau("Palau"),
    Panam("Panam"),
    Papua_New_Guinea("Papus New Guinea"),
    Paraguay("Paraguay"),
    Peru("Peru"),
    Philippines("philippines"),
    Poland("Poland"),
    Portugal("Portugal"),
    Puerto_Rico("Puerto Rico"),
    Qatar("Qatar"),
    Reunion("Reunion"),
    Romania("Romania"),
    Russia("Russia"),
    Rwanda("Rwanda"),
    Saint_Helena("Saint Helena"),
    Saint_Lucia("Saint Lucia"),
    Saint_Vincent_And_The_Grenadines("Saint Vincent and the Grenadines"),
    Samoa("Samoa"),
    San_Marino("San Marino"),
    Saudi_Arabia("Saudi Arabia"),
    Senegal("Senegal"),
    Serbia("Serbia"),
    Seychelles("Seychelles"),
    Sierra_Leone("Sierra Leone"),
    Singapore("Singapore"),
    Slovakia("Slovakia"),
    Slovenia("Slovenia"),
    Solomon_Islands("Solomon Islands"),
    Somalia("Somalia"),
    South_Africa("south Africa"),
    Spain("Spain"),
    Sri_Lanka("Sri Lanka"),
    Sudan("Sudan"),
    Suriname("Suriname"),
    Swaziland("Swaziland"),
    Sweden("Sweden"),
    Switzerland("Switzerland"),
    Syria("Syria"),
    Tajikistan("Tajikistan"),
    Tanzania("Tanzania"),
    Thailand("Thailand"),
    Togo("Togo"),
    Tonga("Tonga"),
    Tunisia("Tunisia"),
    Turkey("Turkey"),
    Turkmenistan("Turkmenistan"),
    Tuvalu("Tuvalu"),
    Uganda("Uganda"),
    Ukraine("Ukraine"),
    United_Arab_Emirates("United Arab Emirates"),
    United_Kingdom("United Kingdom"),
    United_States("United States of America"),
    Uruguay("Uruguay"),
    Uzbekistan("Uzbekistan"),
    Vanuatu("Vanuatu"),
    Venezuela("Venezuela"),
    Vietnam("Vietnam"),
    Virgin_Islands("Virgin Islands"),
    Wallis_And_Futuna("Island And Future"),
    West_Bank("West Bank"),
    Western_Sahara("Western Sahara"),
    Yemen("Yemen"),
    Zambia("Zambia"),
    Zimbabwe("Zimbabwe");

    private final String countries;

    Countries(String countries) {
        this.countries = countries;
    }

    public String getCountries() {
        return countries;
    }
}